### ISSUE TITLE
input image

### ISSUE THREAD

**Issue by cometta** [pokaxpoka/rad_procgen#1]
what is the input image size  for procgen? is it bigger than 64x64x3 ? because the output of crop is smaller right?

**Comment by pokaxpoka** [comment]
as I remember, it is 84x84x3

**Comment by masud99r** [comment]
The Procgen observation is of shape 64x64x3 (https://github.com/openai/procgen). In that case, how the crop works here? https://github.com/pokaxpoka/rad_procgen/blob/master/train_procgen/data_augs.py#L211.
If `self.crop_size = 64`, will it impact the input image?
